version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ./env/mysql.env
    ports:
      - '3307:3307'
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: files/Dockerfile
    container_name: php
    restart: always
    ports:
      - '8085:80'
    depends_on:
      - mysql
    volumes:
      - ./uploads:/var/www/html/uploads  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8087:80'
    env_file:
      - ./env/phpmyadmin.env
    depends_on:
      - mysql

volumes:
  mysql_data:
